# Generated by Django 5.2.17 on 2026-09-29 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='state',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('SUBMETIDO', 'Enviado para distribuição'), ('EM_TRIAGEM', 'Em triagem'), ('AGUARDANDO_CLIENTE', 'Aguardando complemento'), ('ACEITO', 'Aceito na triagem'), ('RECUSADO', 'Recusado'), ('AGUARDANDO_PROCURACAO', 'Aguardando procuração'), ('EM_PREPARACAO', 'Em preparação'), ('EM_ACOMPANHAMENTO', 'Em acompanhamento'), ('ENCERRADO', 'Encerrado')], default='RASCUNHO', max_length=24),
        ),
        migrations.CreateModel(
            name='ServiceAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField()),
                ('reason', models.CharField(max_length=240)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_grants', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
