# Generated by Django 5.2.17 on 2026-10-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_case_state_serviceaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='occurred_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
