# Generated by Django 5.2.17 on 2026-09-25 11:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Mensagem ao caso'), ('INTERNAL', 'Nota interna')], max_length=10)),
                ('client_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='cases.case')),
            ],
            options={
                'indexes': [models.Index(fields=['case', 'visibility', '-created_at'], name='communicati_case_id_e7887f_idx')],
                'constraints': [models.UniqueConstraint(fields=('case', 'author', 'client_id'), name='message_retry_unique')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_key', models.CharField(max_length=80)),
                ('kind', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cases.case')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['recipient', 'read_at', '-created_at'], name='communicati_recipie_dd2d8a_idx')],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'source_key'), name='notification_source_unique')],
            },
        ),
    ]
