# Generated by Django 5.2.17 on 2026-09-29 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
        ('legal', '0002_caseexport_mandatetemplate_generatedmandate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_due_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(null=True)),
                ('cancelled_at', models.DateTimeField(null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('lease_id', models.UUIDField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
                ('last_error', models.CharField(blank=True, max_length=40)),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='email_delivery', to='communication.notification')),
                ('reminder_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='legal.legaltask')),
            ],
        ),
    ]
