// Histórico anterior ao acesso exclusivo da equipe; não faz parte da suíte atual.
const { test, expect } = require('../../frontend/node_modules/@playwright/test');
const { execFileSync } = require('node:child_process');
const { createHmac, randomUUID } = require('node:crypto');
const path = require('node:path');

const root = path.resolve(__dirname, '../..');
const python = process.env.IUSTUS_TEST_PYTHON || path.join(root, 'backend', '.venv', process.platform === 'win32' ? 'Scripts/python.exe' : 'bin/python');
const password = 'Synthetic-Browser-Passphrase-938!';
const clientOrigin = 'http://localhost:3000';
const teamOrigin = 'http://127.0.0.1:3000';
function fixture(action, email) {
  return JSON.parse(execFileSync(python, [path.join(__dirname, 'fixture.py'), action, email], { encoding: 'utf8', windowsHide: true, timeout: 15000 }));
}
function mailLink(email) { return fixture('mail', email).body.match(/http[^\s]+/)[0]; }
function email() { return `e2e-${randomUUID()}@example.test`; }
function otp(secret) {
  const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
  const bits = [...secret].map(c => alphabet.indexOf(c).toString(2).padStart(5, '0')).join('');
  const key = Buffer.from((bits.match(/.{8}/g) || []).map(byte => parseInt(byte, 2)));
  const counter = Buffer.alloc(8); counter.writeBigUInt64BE(BigInt(Math.floor(Date.now() / 30000)));
  const hash = createHmac('sha1', key).update(counter).digest();
  const offset = hash[hash.length - 1] & 15;
  return String((hash.readUInt32BE(offset) & 0x7fffffff) % 1000000).padStart(6, '0');
}
async function signIn(page, origin, address, secret = password) {
  await page.goto(origin + '/acessar');
  await page.getByLabel('E-mail', { exact: true }).fill(address);
  await page.getByLabel('Senha', { exact: true }).fill(secret);
  await page.getByRole('button', { name: 'Acessar plataforma' }).click();
}
async function enroll(page) {
  const secret = await page.getByTestId('mfa-secret').textContent();
  await page.getByLabel('Código do autenticador', { exact: true }).fill(otp(secret));
  await page.getByRole('button', { name: 'Confirmar segundo fator' }).click();
  await expect(page.getByRole('heading', { name: 'Guarde seus códigos de recuperação' })).toBeVisible();
  const codes = await page.locator('.recovery-codes li code').allTextContents();
  await page.getByRole('button', { name: 'Guardei os códigos. Continuar' }).click();
  await expect(page).toHaveURL(/\/advogado$/);
  return codes;
}

test('cliente cadastra, verifica e-mail, acessa painel e redefine senha', async ({ page }) => {
  const address = email();
  await page.goto(clientOrigin + '/acessar');
  await page.getByRole('button', { name: 'Criar conta', exact: true }).click();
  await page.getByLabel('Nome completo').fill('Cliente de Teste');
  await page.getByLabel('E-mail', { exact: true }).fill(address);
  await page.getByLabel('Senha', { exact: true }).fill(password);
  await page.getByRole('checkbox').check();
  await page.getByRole('button', { name: 'Criar minha conta' }).click();
  await expect(page.getByRole('status')).toContainText('Confira seu e-mail');
  await page.goto(mailLink(address));
  await page.getByRole('button', { name: 'Confirmar meu e-mail' }).click();
  await expect(page.getByRole('status')).toContainText('E-mail confirmado');
  await signIn(page, clientOrigin, address);
  await expect(page.getByRole('heading', { name: 'Olá, Cliente de Teste.' })).toBeVisible();
  await page.getByRole('button', { name: 'Sair da conta' }).click();
  await expect(page).toHaveURL(/\/acessar$/);
  await page.getByRole('button', { name: 'Esqueci minha senha' }).click();
  await page.getByLabel('E-mail', { exact: true }).fill(address);
  await page.getByRole('button', { name: 'Enviar recuperação' }).click();
  await expect(page.getByRole('status')).toContainText('instruções');
  await page.goto(mailLink(address));
  const changed = 'Changed-Browser-Passphrase-651!';
  await page.getByLabel('Nova senha').fill(changed);
  await page.getByRole('button', { name: 'Salvar nova senha' }).click();
  await expect(page.getByRole('status')).toContainText('Senha atualizada');
  await signIn(page, clientOrigin, address, changed);
  await expect(page.getByRole('heading', { name: 'Olá, Cliente de Teste.' })).toBeVisible();
});

test('administrador confirma MFA, convida advogado e usa recuperação uma vez', async ({ browser }) => {
  const admin = email(), lawyer = email();
  fixture('admin', admin);
  const context = await browser.newContext();
  const page = await context.newPage();
  await signIn(page, teamOrigin, admin);
  const codes = await enroll(page);
  await page.getByLabel('E-mail do profissional').fill(lawyer);
  await page.getByRole('button', { name: 'Enviar convite' }).click();
  await expect(page.getByRole('status')).toContainText('convite');
  const other = await browser.newContext();
  const professional = await other.newPage();
  await professional.goto(mailLink(lawyer));
  await professional.getByLabel('Nome completo').fill('Advogado de Teste');
  await professional.getByLabel('Senha', { exact: true }).fill(password);
  await professional.getByRole('button', { name: 'Aceitar convite' }).click();
  await expect(professional.getByRole('status')).toContainText('Convite aceito');
  await signIn(professional, teamOrigin, lawyer);
  await enroll(professional);
  await expect(professional.getByRole('heading', { name: 'Olá, Advogado de Teste.' })).toBeVisible();
  await expect(professional.getByRole('heading', { name: 'Convidar advogado' })).toHaveCount(0);
  await page.getByRole('button', { name: 'Sair da conta' }).click();
  await expect(page).toHaveURL(/\/acessar$/);
  await signIn(page, teamOrigin, admin);
  await page.getByLabel('Código do autenticador ou de recuperação').fill(codes[0]);
  await page.getByRole('button', { name: 'Confirmar segundo fator' }).click();
  await expect(page.getByRole('heading', { name: 'Olá, Admin Teste.' })).toBeVisible();
  await other.close(); await context.close();
});

test('rotas e headers de outro portal são recusados', async ({ request }) => {
  expect((await request.get(clientOrigin + '/advogado')).status()).toBe(403);
  expect((await request.get(teamOrigin + '/cliente')).status()).toBe(403);
  const result = await request.get(clientOrigin + '/api/v1/auth/csrf', {
    headers: { 'X-Forwarded-Host': '127.0.0.1:3000', 'X-Iustus-Portal-Host': '127.0.0.1:3000', 'X-Iustus-Proxy-Key': 'forged' },
  });
  expect((await result.json()).portal).toBe('client');
  const login = await request.post(clientOrigin + '/api/v1/auth/login', { data: { email: email(), password } });
  expect(login.status()).toBe(403);
  expect((await login.json()).error.code).toBe('CSRF_FAILED');
  const binary = { headers: { 'Content-Type': 'application/octet-stream' }, data: Buffer.from('test') };
  expect((await request.post(clientOrigin + '/api/v1/cases', binary)).status()).toBe(415);
  expect((await request.post(clientOrigin + `/api/v1/uploads/${randomUUID()}/content`, binary)).status()).toBe(403);
  const tooLarge = await request.post(clientOrigin + `/api/v1/uploads/${randomUUID()}/content`, {
    headers: binary.headers, data: Buffer.alloc(20 * 1024 * 1024 + 1),
  });
  expect(tooLarge.status()).toBe(413);
});

test('caso percorre liberação, triagem, procuração, peça, protocolo e encerramento com isolamento', async ({ browser }) => {
  test.setTimeout(180000);
  const clientEmail = email(), adminEmail = email(), lawyerEmail = email();
  fixture('client', clientEmail); fixture('admin', adminEmail); fixture('lawyer', lawyerEmail);
  const clientContext = await browser.newContext({ viewport: { width: 390, height: 844 } });
  const adminContext = await browser.newContext();
  const lawyerContext = await browser.newContext();
  const clientPage = await clientContext.newPage(), adminPage = await adminContext.newPage(), lawyerPage = await lawyerContext.newPage();
  await signIn(clientPage, clientOrigin, clientEmail);
  await clientPage.getByRole('button', { name: 'Cadastrar ocorrência', exact: true }).click();
  await clientPage.getByLabel('Título do caso').fill('Cobrança contratual fictícia');
  await clientPage.getByLabel('Categoria', { exact: true }).selectOption('CONTRACTS');
  await clientPage.getByLabel('Descrição do que aconteceu', { exact: true }).fill('Informação privada de um contrato inteiramente fictício para testar a triagem.');
  await clientPage.getByLabel('Estou ciente de que família e sucessões não fazem parte do serviço.').check();
  await clientPage.getByRole('button', { name: 'Salvar rascunho', exact: true }).click();
  await expect(clientPage.getByRole('status')).toHaveText('Alteração registrada.');
  await expect(clientPage.getByRole('button', { name: 'Enviar ocorrência para análise' })).toBeDisabled();
  await signIn(adminPage, teamOrigin, adminEmail); await enroll(adminPage);
  await adminPage.getByLabel('E-mail do cliente', {exact: true}).fill(clientEmail);
  await adminPage.getByLabel('Validade da liberação').fill('2027-12-01T12:00');
  await adminPage.getByLabel('Motivo da liberação').fill('Atendimento sintético autorizado pelo escritório.');
  await adminPage.getByRole('button', {name: 'Salvar liberação', exact: true}).click();
  await expect(adminPage.getByText('Liberação atualizada. Casos já enviados permanecem em acompanhamento.', {exact: true})).toBeVisible();
  await clientPage.reload();
  await clientPage.locator('.case-list').getByRole('button', { name: /Cobrança contratual fictícia/ }).click();
  const pdf = Buffer.from('%PDF-1.4\n1 0 obj\n<< /Type /Catalog >>\nendobj\n%%EOF\n');
  await clientPage.getByLabel('Arquivo para anexar').setInputFiles({ name: 'contrato-ficticio.pdf', mimeType: 'application/pdf', buffer: pdf });
  await clientPage.getByRole('button', { name: 'Enviar arquivo', exact: true }).click();
  await expect(clientPage.getByText('Arquivo recebido. Aguarde a verificação e atualize a lista.')).toBeVisible();
  await expect(clientPage.getByRole('button', { name: 'Baixar contrato-ficticio.pdf (v1)', exact: true })).toBeDisabled();
  expect(fixture('document-scan-fixture', clientEmail).available).toBe(1);
  await clientPage.getByRole('button', { name: 'Atualizar documentos', exact: true }).click();
  await expect(clientPage.getByRole('button', { name: 'Baixar contrato-ficticio.pdf (v1)', exact: true })).toBeEnabled();
  const downloadEvent = clientPage.waitForEvent('download');
  await clientPage.getByRole('button', { name: 'Baixar contrato-ficticio.pdf (v1)', exact: true }).click();
  const download = await downloadEvent;
  expect(download.suggestedFilename()).toBe('contrato-ficticio.pdf');
  expect(await download.failure()).toBeNull();
  await clientPage.getByRole('button', { name: 'Enviar ocorrência para análise' }).click();
  await expect(clientPage.locator('.case-detail > .cases-heading > .case-badge')).toHaveText('Enviado para distribuição');
  const reference = (await clientPage.locator('#case-detail-title').innerText()).replace('Caso ', '');
  await signIn(lawyerPage, teamOrigin, lawyerEmail); await enroll(lawyerPage);
  await expect(lawyerPage.getByText('Nenhum caso encontrado neste filtro.')).toBeVisible();
  await adminPage.reload();
  await adminPage.locator('.case-list').getByRole('button', { name: new RegExp(`Caso ${reference}`) }).click();
  await expect(adminPage.getByText('Informação privada de um contrato', { exact: false })).toHaveCount(0);
  await adminPage.getByLabel('Advogado responsável').selectOption({ label: `Advogado Teste — ${lawyerEmail}` });
  await adminPage.getByLabel('Motivo administrativo').fill('Distribuição privada que não deve aparecer ao cliente.');
  await adminPage.getByRole('button', { name: 'Salvar responsável' }).click();
  await expect(adminPage.getByRole('status')).toHaveText('Alteração registrada.');
  await lawyerPage.reload();
  await lawyerPage.locator('.case-list').getByRole('button', { name: /Cobrança contratual fictícia/ }).click();
  await lawyerPage.getByRole('button', { name: 'Iniciar triagem' }).click();
  await lawyerPage.getByLabel('Informações a complementar').fill('Informe quando ocorreu o fato fictício.');
  await lawyerPage.getByRole('button', { name: 'Solicitar complemento' }).click();
  await expect(lawyerPage.locator('.case-detail > .cases-heading > .case-badge')).toHaveText('Aguardando complemento');
  await clientPage.reload();
  await clientPage.locator('.case-list').getByRole('button', { name: /Cobrança contratual fictícia/ }).click();
  await clientPage.getByLabel('Sua resposta').fill('O fato fictício ocorreu em quinze de setembro.');
  await clientPage.getByLabel('Anexar contrato-ficticio.pdf (v1)', { exact: true }).check();
  await clientPage.getByRole('button', { name: 'Enviar complemento', exact: true }).click();
  await expect(clientPage.getByText('Aguardando conferência pelo responsável.')).toBeVisible();
  await expect(clientPage.getByText('Distribuição privada que não deve aparecer ao cliente.')).toHaveCount(0);
  expect(await clientPage.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  if (process.env.IUSTUS_CASE_SCREENSHOT) await clientPage.screenshot({ path: process.env.IUSTUS_CASE_SCREENSHOT, fullPage: true });
  await lawyerPage.reload();
  await lawyerPage.locator('.case-list').getByRole('button', { name: /Cobrança contratual fictícia/ }).click();
  await expect(lawyerPage.getByRole('button', { name: 'Anexo: contrato-ficticio.pdf (v1)', exact: true })).toBeVisible();
  const lawyerDownload = lawyerPage.waitForEvent('download');
  await lawyerPage.getByRole('button', { name: 'Anexo: contrato-ficticio.pdf (v1)', exact: true }).click();
  expect((await lawyerDownload).suggestedFilename()).toBe('contrato-ficticio.pdf');
  await lawyerPage.getByLabel('Resultado da conferência').fill('Data recebida e conferida para o teste.');
  await lawyerPage.getByRole('button', { name: 'Conferir e retomar triagem' }).click();
  await lawyerPage.getByLabel('Escopo compatível:', { exact: false }).check();
  await lawyerPage.getByLabel('Conflito de interesses analisado').check();
  await lawyerPage.getByLabel('Informações suficientes para decidir o atendimento').check();
  await lawyerPage.getByLabel('Justificativa visível ao cliente').fill('Aceite fictício após análise das informações e do escopo.');
  await lawyerPage.getByRole('button', { name: 'Aprovar caso e preparar procuração', exact: true }).click();
  await expect(lawyerPage.locator('.case-detail > .cases-heading > .case-badge')).toHaveText('Aceito na triagem');
  await clientPage.reload();
  await clientPage.locator('.case-list').getByRole('button', { name: /Cobrança contratual fictícia/ }).click();
  await expect(clientPage.locator('.case-detail > .cases-heading > .case-badge')).toHaveText('Aceito na triagem');
  await expect(clientPage.getByText('Aceite fictício após análise das informações e do escopo.')).toBeVisible();
  await lawyerPage.getByLabel('Registrar como nota interna', { exact: false }).check();
  await lawyerPage.getByLabel('Nota interna', { exact: true }).fill('Estratégia restrita de teste.');
  await lawyerPage.getByRole('button', { name: 'Salvar nota interna', exact: true }).click();
  await expect(lawyerPage.locator('.message-list')).toContainText('Estratégia restrita de teste.');
  await lawyerPage.getByLabel('Registrar como nota interna', { exact: false }).uncheck();
  await lawyerPage.getByLabel('Sua mensagem', { exact: true }).fill('Recebemos os documentos e seguimos com a análise.');
  await lawyerPage.getByRole('button', { name: 'Enviar mensagem', exact: true }).click();
  await expect(lawyerPage.locator('.message-list')).toContainText('Recebemos os documentos');
  await clientPage.getByRole('button', { name: 'Atualizar conversa' }).click();
  await expect(clientPage.locator('.message-list')).toContainText('Recebemos os documentos');
  await expect(clientPage.getByText('Estratégia restrita de teste.')).toHaveCount(0);
  await clientPage.getByLabel('Sua mensagem', { exact: true }).fill('<img src=x onerror=alert(1)> Obrigado pelo retorno.');
  await clientPage.getByRole('button', { name: 'Enviar mensagem', exact: true }).click();
  await expect(clientPage.locator('.message-list')).toContainText('<img src=x onerror=alert(1)>');
  await expect(clientPage.locator('.message-list img')).toHaveCount(0);
  await expect(clientPage.locator('.notification-list')).toContainText('Você recebeu uma mensagem no caso');
  const notice = clientPage.locator('.notification-list li').filter({ hasText: 'Você recebeu uma mensagem no caso' });
  await notice.getByRole('button', { name: 'Marcar como lido' }).click();
  await expect(notice.locator('.notice-label')).toContainText('Lido');
  await clientPage.getByLabel('Somente não lidos').check();
  await expect(clientPage.locator('.notification-list')).not.toContainText('Você recebeu uma mensagem no caso');
  await clientPage.getByLabel('Somente não lidos').uncheck();
  await expect(clientPage.locator('.notification-list')).toContainText('Você recebeu uma mensagem no caso');
  await notice.getByRole('button', { name: 'Abrir caso' }).click();
  await expect(clientPage.getByLabel('Sua mensagem', { exact: true })).toBeVisible();
  await expect(clientPage.locator('.message-list')).toContainText('Obrigado pelo retorno.');
  await expect(clientPage.locator('.dashboard-metrics')).toContainText('Avisos não lidos');
  expect(await clientPage.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  if (process.env.IUSTUS_DASHBOARD_SCREENSHOT) {
    await clientPage.locator('.case-messages').screenshot({ path: process.env.IUSTUS_DASHBOARD_SCREENSHOT.replace('.png', '-conversation.png') });
    await clientPage.evaluate(() => window.scrollTo(0, 0));
    await clientPage.screenshot({ path: process.env.IUSTUS_DASHBOARD_SCREENSHOT });
    await lawyerPage.evaluate(() => window.scrollTo(0, 0));
    await lawyerPage.screenshot({ path: process.env.IUSTUS_DASHBOARD_SCREENSHOT.replace('.png', '-team.png') });
  }
  async function upload(page, filename) {
    await page.getByLabel('Arquivo para anexar').setInputFiles({name: filename, mimeType: 'application/pdf', buffer: pdf});
    await page.getByRole('button', {name: 'Enviar arquivo', exact: true}).click();
    await expect(page.getByText('Arquivo recebido. Aguarde a verificação e atualize a lista.')).toBeVisible();
    fixture('document-scan-fixture', clientEmail);
    await page.getByRole('button', {name: 'Atualizar documentos', exact: true}).click();
    await expect(page.getByRole('button', {name: `Baixar ${filename} (v1)`, exact: true})).toBeEnabled();
  }
  await lawyerPage.getByText('Cadastrar ou revisar modelo', {exact: true}).click();
  await lawyerPage.getByLabel('Nome do modelo', {exact: true}).fill('Procuração sintética de navegador');
  await lawyerPage.getByLabel('Texto jurídico do modelo').fill('Outorgante: {{cliente_nome}}. Advogado: {{advogado_nome}}, OAB {{advogado_oab}}. Texto fictício exclusivo para teste do sistema. Data {{data_emissao}}, caso {{caso_referencia}}.');
  await lawyerPage.getByLabel('Revisei e aprovo o texto e os poderes deste modelo').check();
  await lawyerPage.getByRole('button', {name: 'Salvar modelo aprovado'}).click();
  await expect(lawyerPage.getByText('Modelo aprovado e salvo como nova versão.', {exact: true})).toBeVisible();
  await lawyerPage.getByLabel('Nome do outorgante', {exact: true}).fill('Cliente de Teste');
  await lawyerPage.getByLabel('Inscrição OAB', {exact: true}).fill('OAB-TESTE');
  await lawyerPage.getByLabel('Conferi os dados e o modelo para este caso').check();
  await lawyerPage.getByRole('button', {name: 'Gerar PDF da procuração'}).click();
  await expect(lawyerPage.getByText('Procuração gerada. Baixe e confira o PDF antes de solicitar a assinatura.', {exact: true})).toBeVisible();
  const generatedDownload = lawyerPage.waitForEvent('download');
  await lawyerPage.getByRole('button', {name: 'Baixar procuração gerada', exact: true}).click();
  const generatedPdf = await generatedDownload;
  expect(generatedPdf.suggestedFilename()).toMatch(/^procuracao-.*-1\.pdf$/);
  expect(require('node:fs').readFileSync(await generatedPdf.path()).subarray(0, 5).toString()).toBe('%PDF-');
  await lawyerPage.locator('.mandate-generator').screenshot({path: path.join(root, '.local/mandate-generator.png')});
  await lawyerPage.getByLabel('Etapas contratadas', {exact: true}).fill('Preparação da peça, protocolo e acompanhamento do caso sintético.');
  await lawyerPage.getByLabel('Posição do cliente').selectOption('DEFENDANT');
  await expect(lawyerPage.getByLabel('Documento verificado', {exact: false})).not.toHaveValue('');
  await lawyerPage.getByRole('button', {name: 'Enviar procuração deste caso para assinatura', exact: true}).click();
  await expect(lawyerPage.locator('.case-detail > .cases-heading > .case-badge')).toHaveText('Aguardando procuração');
  await clientPage.reload();
  await clientPage.locator('.case-list').getByRole('button', {name: /Cobrança contratual fictícia/}).click();
  await upload(clientPage, 'procuracao-devolvida.pdf');
  await clientPage.getByLabel('Documento verificado', {exact: false}).selectOption({label: 'procuracao-devolvida.pdf · v1'});
  await clientPage.getByRole('button', {name: 'Entregar procuração assinada'}).click();
  await expect(clientPage.locator('.legal-workflow').getByText('Etapa registrada.', {exact: true})).toBeVisible();
  await lawyerPage.getByRole('button', {name: 'Atualizar andamento'}).click();
  await lawyerPage.getByLabel('Conferi a procuração assinada').check();
  await lawyerPage.getByRole('button', {name: 'Confirmar procuração', exact: true}).click();
  await expect(lawyerPage.locator('.case-detail > .cases-heading > .case-badge')).toHaveText('Em preparação');
  await lawyerPage.getByLabel('Minuta interna da peça').fill('Peça sintética revisada para testar a entrega ao cliente.');
  await lawyerPage.getByRole('button', {name: 'Salvar minuta', exact: true}).click();
  await expect(lawyerPage.locator('.legal-workflow').getByText('Etapa registrada.', {exact: true})).toBeVisible();
  await clientPage.getByRole('button', {name: 'Atualizar andamento'}).click();
  await expect(clientPage.getByText('Peça sintética revisada para testar a entrega ao cliente.', {exact: true})).toHaveCount(0);
  await lawyerPage.getByLabel('Revisei os dados e confirmo a ação selecionada').check();
  await lawyerPage.getByRole('button', {name: 'Publicar peça revisada'}).click();
  await expect(lawyerPage.locator('.legal-workflow details')).toContainText('Peça sintética revisada');
  await upload(lawyerPage, 'comprovante-sintetico.pdf');
  await lawyerPage.getByLabel('Órgão do protocolo').fill('Órgão de teste');
  await lawyerPage.getByLabel('Número do processo', {exact: true}).fill('PROCESSO-SINTETICO');
  await lawyerPage.getByLabel('Número do protocolo', {exact: true}).fill('PROTOCOLO-SINTETICO');
  await lawyerPage.getByLabel('Documento verificado', {exact: false}).selectOption({label: 'comprovante-sintetico.pdf · v1'});
  await lawyerPage.getByLabel('Revisei os dados e confirmo a ação selecionada').check();
  await lawyerPage.getByRole('button', {name: 'Registrar protocolo externo'}).click();
  await expect(lawyerPage.locator('.case-detail > .cases-heading > .case-badge')).toHaveText('Em acompanhamento');
  await lawyerPage.getByLabel('Movimentação, motivo ou resultado').fill('Audiência agendada para o teste.');
  await lawyerPage.getByLabel('Tipo de compromisso').selectOption('HEARING');
  await lawyerPage.getByLabel('Título do compromisso').fill('Audiência de teste');
  await lawyerPage.getByLabel('Data do compromisso').fill('2027-01-15T14:30');
  await lawyerPage.getByRole('button', {name: 'Adicionar compromisso'}).click();
  await expect(lawyerPage.locator('.legal-tasks')).toContainText('Audiência de teste');
  await lawyerPage.getByLabel('Movimentação, motivo ou resultado').fill('Atendimento concluído e resultado comunicado.');
  await lawyerPage.getByLabel('Revisei os dados e confirmo a ação selecionada').check();
  await expect(lawyerPage.getByRole('button', {name: 'Encerrar atendimento'})).toBeDisabled();
  await lawyerPage.getByRole('button', {name: 'Concluir compromisso'}).click();
  await expect(lawyerPage.locator('.legal-tasks')).toContainText('Concluído');
  await lawyerPage.getByLabel('Movimentação, motivo ou resultado').fill('Atendimento concluído e resultado comunicado.');
  await lawyerPage.getByLabel('Revisei os dados e confirmo a ação selecionada').check();
  await lawyerPage.getByRole('button', {name: 'Encerrar atendimento'}).click();
  await expect(lawyerPage.locator('.case-detail > .cases-heading > .case-badge')).toHaveText('Encerrado');
  await clientPage.reload();
  await clientPage.locator('.case-list').getByRole('button', {name: /Cobrança contratual fictícia/}).click();
  await expect(clientPage.locator('.case-detail > .cases-heading > .case-badge')).toHaveText('Encerrado');
  await expect(clientPage.locator('.legal-workflow details')).toContainText('Peça sintética revisada');
  expect(await clientPage.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await clientPage.getByRole('button', {name: 'Preparar dossiê', exact: true}).click();
  await expect(clientPage.getByText('Dossiê preparado.', {exact: false})).toBeVisible();
  const archiveDownload = clientPage.waitForEvent('download');
  await clientPage.getByRole('button', {name: 'Baixar dossiê ZIP', exact: true}).click();
  const archive = await archiveDownload;
  expect(archive.suggestedFilename()).toMatch(/^dossie-.*\.zip$/);
  const inspected = JSON.parse(execFileSync(python, ['-c', 'import sys,json,zipfile; z=zipfile.ZipFile(sys.argv[1]); text="\\n".join(z.read(n).decode("utf-8") for n in z.namelist() if n.endswith((".json",".txt"))); print(json.dumps({"files":z.namelist(),"private": "Estratégia restrita de teste." in text,"published":"Peça sintética revisada" in text}))', await archive.path()], {encoding:'utf8', windowsHide:true}));
  expect(inspected.files).toContain('manifesto.json');
  expect(inspected.files.some(name => name.endsWith('.pdf'))).toBe(true);
  expect(inspected.private).toBe(false);
  expect(inspected.published).toBe(true);
  await clientPage.locator('.case-export').screenshot({path: path.join(root, '.local/case-export-mobile.png')});
  await clientPage.locator('.legal-workflow').screenshot({path: path.join(root, '.local/workflow-client.png')});
  await lawyerPage.locator('.legal-workflow').screenshot({path: path.join(root, '.local/workflow-lawyer.png')});
  await clientPage.getByLabel('Nome de exibição').fill('Cliente atualizado');
  await clientPage.getByLabel('Receber avisos do atendimento por e-mail').uncheck();
  await clientPage.getByRole('button', {name: 'Salvar perfil', exact: true}).click();
  await expect(clientPage.getByText('Preferências salvas.', {exact: true})).toBeVisible();
  await clientPage.reload();
  await expect(clientPage.getByLabel('Nome de exibição')).toHaveValue('Cliente atualizado');
  await expect(clientPage.getByLabel('Receber avisos do atendimento por e-mail')).not.toBeChecked();
  await clientPage.getByLabel('Tipo de solicitação').selectOption('ACCESS');
  await clientPage.getByLabel('Descreva sua solicitação').fill('Solicito acesso aos meus dados sintéticos.');
  await clientPage.getByRole('button', {name: 'Registrar solicitação', exact: true}).click();
  await expect(clientPage.getByText('Solicitação registrada para análise.', {exact: true})).toBeVisible();
  await adminPage.getByRole('button', {name: 'Atualizar solicitações', exact: true}).click();
  const request = adminPage.locator('li').filter({hasText: 'Solicito acesso aos meus dados sintéticos.'});
  await request.getByLabel('Resposta à solicitação').fill('Dados sintéticos disponíveis no dossiê do atendimento.');
  await request.getByRole('button', {name: 'Registrar resposta', exact: true}).click();
  await expect(request).toContainText('Respondida');
  await clientPage.getByRole('button', {name: 'Atualizar solicitações', exact: true}).click();
  await expect(clientPage.getByText('Resposta: Dados sintéticos disponíveis no dossiê do atendimento.', {exact: true})).toBeVisible();
  expect(await clientPage.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await clientPage.locator('#minha-conta').screenshot({path: path.join(root, '.local/account-mobile.png')});
  await adminPage.getByRole('button', {name: 'Atualizar usuários', exact: true}).click();
  const account = adminPage.locator('li').filter({has: adminPage.getByRole('button', {name: 'Suspender acesso', exact: true})}).filter({hasText: clientEmail});
  await account.getByRole('button', {name: 'Suspender acesso', exact: true}).click();
  await adminPage.getByLabel('Motivo da alteração').fill('Suspensão sintética para validar revogação de sessão.');
  await adminPage.getByRole('button', {name: 'Confirmar alteração de acesso', exact: true}).click();
  await expect(adminPage.getByText('Acesso atualizado. As sessões anteriores foram invalidadas.', {exact: true})).toBeVisible();
  await clientPage.reload();
  await expect(clientPage).toHaveURL(/\/acessar$/);
  await clientContext.close(); await adminContext.close(); await lawyerContext.close();
});
