from django.urls import path

from . import mobile, mobile_flows as flows, views

urlpatterns = [
    path("mobile/auth/context", flows.ContextView.as_view()),
    path("mobile/auth/register", flows.RegisterView.as_view()),
    path("mobile/auth/verify", flows.VerifyView.as_view()),
    path("mobile/auth/resend", flows.ResendView.as_view()),
    path("mobile/auth/reset", flows.ResetView.as_view()),
    path("mobile/billing/activate", flows.MemberActivateView.as_view()),
    path("mobile/billing/resend", flows.MemberResendView.as_view()),
    path("mobile/billing/plan", flows.MobilePlanView.as_view()),
    path("mobile/me", flows.ProfileView.as_view()),
    path("mobile/cases/catalog", flows.CatalogView.as_view()),
    path("mobile/cases/<uuid:case_id>/submit", flows.SubmitView.as_view()),
    path("mobile/cases/<uuid:case_id>/requests", flows.RequestsView.as_view()),
    path("mobile/cases/<uuid:case_id>/requests/<uuid:request_id>/response", flows.RespondView.as_view()),
    path("mobile/cases/<uuid:case_id>/workflow", flows.WorkView.as_view()),
    path("mobile/cases/<uuid:case_id>/documents", flows.DocumentsView.as_view()),
    path("mobile/cases/<uuid:case_id>/documents/uploads", flows.DocumentsView.as_view()),
    path("mobile/documents/<uuid:document_id>/versions", flows.VersionsView.as_view()),
    path("mobile/documents/<uuid:document_id>/versions/<uuid:version_id>/content", flows.DownloadView.as_view()),
    path("mobile/uploads/<uuid:upload_id>/content", flows.UploadContentView.as_view()),
    path("mobile/uploads/<uuid:upload_id>/authorize", flows.AuthorizeView.as_view()),
    path("mobile/uploads/<uuid:upload_id>/complete", flows.CompleteView.as_view()),
    path("mobile/privacy/requests", flows.PrivacyRequestsView.as_view()),
    path("mobile/notifications", flows.NoticesView.as_view()),
    path("mobile/notifications/<uuid:notification_id>/read", flows.ReadNoticeView.as_view()),
    path("mobile/auth/login", mobile.MobileLoginView.as_view()),
    path("mobile/auth/recovery", mobile.MobileRecoveryView.as_view()),
    path("mobile/auth/logout", mobile.MobileLogoutView.as_view()),
    path("mobile/dashboard", mobile.MobileDashboardView.as_view()),
    path("mobile/cases/<uuid:case_id>/proposals", mobile.MobileProposalsView.as_view()),
    path("mobile/cases/<uuid:case_id>/proposals/<uuid:proposal_id>/decision", mobile.MobileProposalDecisionView.as_view()),
    path("mobile/cases", mobile.MobileCasesView.as_view()),
    path("mobile/cases/<uuid:case_id>", mobile.MobileCaseView.as_view()),
    path("mobile/cases/<uuid:case_id>/timeline", mobile.MobileTimelineView.as_view()),
    path("mobile/cases/<uuid:case_id>/messages", mobile.MobileMessagesView.as_view()),
    path("auth/csrf", views.CSRFView.as_view()),
    path("auth/register", views.RegisterView.as_view()),
    path("auth/verify", views.VerifyView.as_view()),
    path("auth/resend", views.ResendView.as_view()),
    path("auth/login", views.LoginView.as_view()),
    path("auth/logout", views.LogoutView.as_view()),
    path("auth/recovery", views.RecoveryView.as_view()),
    path("auth/reset", views.ResetView.as_view()),
    path("auth/mfa/enroll", views.EnrollView.as_view()),
    path("auth/mfa/verify", views.MFAView.as_view()),
    path("auth/invitations/accept", views.AcceptInviteView.as_view()),
    path("admin/invitations", views.InviteView.as_view()),
    path("me", views.MeView.as_view()),
    path("dashboard/client", views.ClientDashboardView.as_view()),
    path("dashboard/team", views.TeamDashboardView.as_view()),
]
