# Generated by Django 5.2.17 on 2026-10-05 20:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_key', models.CharField(max_length=64, unique=True)),
                ('session_digest', models.CharField(max_length=64)),
                ('amount', models.PositiveIntegerField()),
                ('environment', models.CharField(max_length=12)),
                ('policy_version', models.CharField(max_length=80)),
                ('status', models.CharField(default='CREATING', max_length=24)),
                ('checkout_id', models.CharField(max_length=80, null=True, unique=True)),
                ('payment_url', models.URLField(blank=True, max_length=1000)),
                ('provider_order_id', models.CharField(max_length=80, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(null=True)),
                ('checked_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='billing.order')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('digest', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('provider_order_id', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField(null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=40)),
                ('lease_id', models.UUIDField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.order')),
            ],
        ),
    ]
