# Generated by Django 5.2.17 on 2026-10-07 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='encrypted_customer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payload_digest',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='BillingIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(max_length=12)),
                ('cpf_digest', models.CharField(max_length=64)),
                ('encrypted_cpf', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('environment', 'cpf_digest'), name='billing_unique_cpf'), models.UniqueConstraint(fields=('environment', 'user'), name='billing_unique_user')],
            },
        ),
    ]
