# Generated by Django 5.2.17 on 2026-10-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_order_encrypted_customer_order_payload_digest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='installments',
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='order',
            name='plan_version',
            field=models.CharField(default='annual-legacy-v1', max_length=80),
        ),
    ]
