# Generated by Django 5.2.17 on 2026-09-29 18:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('ACCESS', 'Acesso'), ('CORRECTION', 'Correção'), ('DELETION', 'Exclusão'), ('OTHER', 'Outro')], max_length=16)),
                ('description', models.TextField()),
                ('status', models.CharField(default='OPEN', max_length=16)),
                ('response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='privacy_resolutions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
