# Generated by Django 5.2.17 on 2026-09-21 18:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='cases.case')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('filename', models.CharField(max_length=180)),
                ('declared_mime', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveIntegerField()),
                ('object_key', models.CharField(max_length=64, unique=True)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('detected_mime', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('UPLOADING', 'Aguardando envio'), ('QUARANTINED', 'Aguardando verificação'), ('SCANNING', 'Em verificação'), ('AVAILABLE', 'Disponível'), ('REJECTED', 'Arquivo recusado'), ('ERROR', 'Verificação indisponível')], default='UPLOADING', max_length=16)),
                ('uploaded_at', models.DateTimeField(null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scanned_at', models.DateTimeField(null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_id', models.UUIDField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
                ('last_error', models.CharField(blank=True, max_length=40)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='documents.document')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='cases.informationrequest')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.documentversion')),
            ],
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['status', 'available_at'], name='documents_d_status_b22605_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'number'), name='document_version_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.CheckConstraint(condition=models.Q(('number__gte', 1)), name='document_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gte', 1), ('size_bytes__lte', 20971520)), name='document_size_limit'),
        ),
        migrations.AddConstraint(
            model_name='requestattachment',
            constraint=models.UniqueConstraint(fields=('request', 'version'), name='request_attachment_unique'),
        ),
    ]
