# Generated by Django 5.2.17 on 2026-09-29 17:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0002_alter_case_state_serviceaccess'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('DEADLINE', 'Prazo'), ('HEARING', 'Audiência'), ('STAGE', 'Etapa')], max_length=12)),
                ('title', models.CharField(max_length=200)),
                ('due_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(null=True)),
                ('outcome', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_tasks', to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='LegalWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.TextField(blank=True)),
                ('client_position', models.CharField(blank=True, max_length=12)),
                ('process_number', models.CharField(blank=True, max_length=100)),
                ('authority', models.CharField(blank=True, max_length=200)),
                ('draft', models.TextField(blank=True)),
                ('published_text', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(null=True)),
                ('protocol', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='legal_work', to='cases.case')),
                ('mandate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mandate_work', to='documents.documentversion')),
                ('receipt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='protocol_work', to='documents.documentversion')),
                ('signed_mandate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_work', to='documents.documentversion')),
            ],
        ),
    ]
