# Generated by Django 5.2.17 on 2026-09-29 17:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_case_state_serviceaccess'),
        ('documents', '0001_initial'),
        ('legal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_version', models.PositiveIntegerField()),
                ('object_key', models.CharField(max_length=32, unique=True)),
                ('sha256', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveIntegerField()),
                ('expires_at', models.DateTimeField()),
                ('purged_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cases.case')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MandateTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('family', models.UUIDField(default=uuid.uuid4)),
                ('number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('sha256', models.CharField(max_length=64)),
                ('approved_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedMandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('fields', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_mandates', to='cases.case')),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='documents.documentversion')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='legal.mandatetemplate')),
            ],
        ),
        migrations.AddConstraint(
            model_name='mandatetemplate',
            constraint=models.UniqueConstraint(fields=('family', 'number'), name='mandate_template_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='generatedmandate',
            constraint=models.UniqueConstraint(fields=('case', 'number'), name='mandate_generation_number_unique'),
        ),
    ]
