# Generated by Django 5.2.17 on 2026-10-07 13:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_occurred_on'),
        ('legal', '0002_caseexport_mandatetemplate_generatedmandate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('scope', models.TextField()),
                ('fee_cents', models.PositiveBigIntegerField()),
                ('expenses', models.TextField()),
                ('payment_terms', models.TextField()),
                ('valid_until', models.DateTimeField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('SUPERSEDED', 'Superseded')], default='OPEN', max_length=12)),
                ('decided_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_proposals', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_proposals', to='cases.case')),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('case', 'number'), name='proposal_case_number_unique'), models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('case',), name='proposal_one_open_per_case'), models.CheckConstraint(condition=models.Q(('number__gte', 1)), name='proposal_positive_number'), models.CheckConstraint(condition=models.Q(models.Q(('decided_at__isnull', True), ('decided_by__isnull', True), ('status__in', ['OPEN', 'SUPERSEDED'])), models.Q(('decided_at__isnull', False), ('decided_by__isnull', False), ('status__in', ['ACCEPTED', 'DECLINED'])), _connector='OR'), name='proposal_decision_consistent')],
            },
        ),
    ]
