# Generated by Django 5.2.17 on 2026-09-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_identityemail_mfadevice_ratelimitbucket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='case_email_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
