# Generated by Django 5.2.17 on 2026-10-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_user_case_email_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiontoken',
            name='purpose',
            field=models.CharField(choices=[('VERIFY', 'Verify'), ('RESET', 'Reset'), ('INVITE', 'Invite'), ('MEMBER', 'Member')], max_length=10),
        ),
    ]
