# Generated by Django 5.2.17 on 2026-10-07 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_alter_actiontoken_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileSession',
            fields=[
                ('digest', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('auth_version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('last_active_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
